### ISSUE TITLE
Upstream to containerd?

### ISSUE THREAD

**Issue by Zalastax** [XenitAB/spegel#13]
This looks like a great solution to a common problem! Do you think it would be worthwhile to aim for an upstream contribution to containerd?

**Comment by phillebaba** [comment]
There is an issue in both Kubernetes and Containerd asking for this feature. Does not seem like either of them has gained traction really.

https://github.com/kubernetes/kubernetes/issues/114424
https://github.com/containerd/containerd/issues/7865

The current implementation relies on Kubernetes to do service discovery to join the DHT. I guess that could be solved without Kubernetes. At the same time this may be out of scope for the Containerd project as it would add a lot of complexity.

**Comment by phillebaba** [comment]
This will most likely not occur in the near future, closing for now.
