### ISSUE TITLE
Failed to walk image manifests

### ISSUE THREAD

**Issue by noyoshi** [XenitAB/spegel#140]
Hi! I just installed spegel to my cluster, and some of the pods in the daemonset get this cryptic error and crash loop 

```
Defaulted container "registry" out of: registry, configuration (init)
{"level":"info","ts":1688689161.8643885,"logger":"p2p","caller":"routing/p2p.go:63","msg":"starting p2p router","id":"/ip4/:)/tcp/5001/p2p/12D3KooWD6pXCqqMcVeBXtoNQQJRX2fTKfj5Dc98WCs7yoTQLGcy"}
{"level":"info","ts":1688689161.8646646,"caller":"build/main.go:160","msg":"running registry","addr":":5000"}
I0707 00:19:21.865702       1 leaderelection.go:245] attempting to acquire leader lease spegel/spegel-leader-election...
{"level":"info","ts":1688689161.8717268,"caller":"state/state.go:44","msg":"running scheduled image state update"}
{"level":"error","ts":1688689162.1034093,"caller":"build/main.go:68","msg":"","error":"failed to update all images: failed to walk image manifests: content digest sha256:190d5c74da93b56c3fcd4e08603834c9b20a5149214a369a5705b37ed62c2c72: not found","stacktrace":"main.main\n\t/build/main.go:68\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

Any idea what this is about? Thanks!

**Comment by noyoshi** [comment]
cluster is in EKS, using version `v1.24.14-eks-c12679a`

**Comment by phillebaba** [comment]
@noyoshi I saw something similar happen yesterday and I think it has to do with how platforms are detected. Currently looking into this right now as a prio. Will cut a new release as soon as it is fixed. I just need to reproduce this issue myself first.

**Comment by phillebaba** [comment]
@noyoshi are you by chance running ARM nodes in EKS?

**Comment by juwalter** [comment]
@phillebaba this one, right? https://github.com/XenitAB/spegel/blob/e07baedcc8a98813736ed8796e65b053e2186905/internal/oci/containerd.go#L92

**Comment by noyoshi** [comment]
@phillebaba nope! Just x86 - they are all `t3.xlarge` nodes. I did notice that they have quite a few pods on them - might be a resource issue I wonder?

**Comment by phillebaba** [comment]
I figured out the issue, it has to do with how platforms are parsed in the manifest. When it chooses the wrong platform this issue is triggered. I have solved the issue but writing a test to limit regression. You will probably have better luck using v0.0.7 until I can get a v0.0.9 released. Hopefully that will be tomorrow.

**Comment by noyoshi** [comment]
thank you!

**Comment by noyoshi** [comment]
yup! problem went away when I downgraded to 0.0.7.

**Comment by phillebaba** [comment]
@noyoshi thanks for raising the issue, this has most likely impacted other users also. I have fixed the issue and also added some tests that most likely should have existed before. I have also cut a v0.0.9 release containing the fix that you should be able to use.

Please consider adding your organization to the [Adotpers list](https://github.com/XenitAB/spegel/blob/main/ADOPTERS.md) if you end up using Spegel at scale.

**Comment by dimm0** [comment]
Are you sure it's fixed? One of new x85_64 nodes in the cluster is giving me `exec /bin/bash: exec format error`, and I'm afraid it's got an image from an arm node also existing in the cluster...
