### ISSUE TITLE
Private images?

### ISSUE THREAD

**Issue by dimm0** [XenitAB/spegel#167]
Hi,

Is it possible to have private images (the ones that can only be pulled with a password) to not be cached? Seems like spegel is making it possible to pull the private images without any password from cache.

**Comment by phillebaba** [comment]
This is a general issue with Kubernetes that Spegel exacerbates. Currently in Kubernetes a Pod with an image pull policy `IfNotPresent` will never pull if the image is already present on the node. Meaning that all Pods have access to all private images in the cluster, as long as they are scheduled on the correct node with the private image. This is also stated in the Kubernetes documentation.

> Cluster with proprietary images, a few of which require stricter access control.
> * Ensure AlwaysPullImages admission controller is active. Otherwise, all Pods potentially have access to all images.
> * Move sensitive data into a "Secret" resource, instead of packaging it in an image.

https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry

This a general challenge in any type of cache in front of authenticated content, as it is not able to authenticate the credentials. On top of that Containerd will not include pull secrets when fetching images from a mirror, which is reasonable.

Having said that I can see why you would want such a feature. I did some quick tests and it seems like it is going to be hard to determine from the request if the image originates from a private registry. The ideal solution would be to add a new option to disable mirroring private images. I will have a look at the OCI spec to see if there is a way to determine this from image manifests or requests.

Now if this is not possible we would have to look at other less ideal options. In your use case are these private images coming from public registries like Docker Hub and GHCR or are they from private registries? My thought is if we could add some sort of filtering to enable opting out of mirroring specific images.

**Comment by phillebaba** [comment]
The issue https://github.com/kubernetes/kubernetes/issues/18787 exists in Kubernetes which discusses possible solutions. As stated there the only mitigation is to enforce pull policy always. The best way forward may be to aim to be compliant with the AlwaysPull admission controller, as that is the official mitigation.

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages

**Comment by dimm0** [comment]
Great, thanks for the explanation!
