### ISSUE TITLE
Question - Image Layer Locations

### ISSUE THREAD

**Issue by noyoshi** [XenitAB/spegel#224]
LMK if there is a better way to ask this, but my team was wondering how images are stored on nodes in the cluster. If you pull an image to a node, and its not in the spegel cache in the cluster, does that image + all associated layers stay on that one node, or does spegel try to distribute the layers throughout all nodes in the cluster? 

Wondering because our application runs as 1 pod / node a lot of times, and was wondering if all the layers of that pod's containers are kept on that node. We have ML compute pods + nodes coming up and down a lot so if the images all stay on the same node, then we would have a lot of cold start situations. 

Thanks!

**Comment by nandakumar12** [comment]
@noyoshi spegel doesn't pull image on its own, It will just act as an mirror registry. When It couldn't find the requested image/layer on the node its just returns 404 to containerd. Then containerd actually pulls the image from the remote registry and store all the layers in the same node.

PS: spgel doesn't distribute layers across nodes. Spegel pods just advertises the layer metadata with each other, when a peer with requested layer is found that peer will actually transmit the layer to the original requester.

**Comment by noyoshi** [comment]
gotcha, thanks!
