### ISSUE TITLE
topologyKeys on service should be optional

### ISSUE THREAD

**Issue by fberube-psee** [XenitAB/spegel#25]
topologyKeys on service chart template, should be optional, since not supported by all potential configurations

**Comment by fberube-psee** [comment]
Also
[Dashboard](https://grafana.com/grafana/dashboards/18089-spegel-stateless-cluster-local-oci-registry-mirror/)

**Comment by phillebaba** [comment]
@fberube-psee you are right they should be removed, and replaced by the new topology annotation. Will get that done.

Great work with the dashboard. I am not sure if we should host the dashboard in this repo considering the license situation with Grafana, but I will add a link in the Readme to it so other users can find it!
