### ISSUE TITLE
Q: Is it possible to selective disable part of metrics?

### ISSUE THREAD

**Issue by evgkrsk** [XenitAB/spegel#255]
Is it possible to disable libp2p_* prefix in /metrics response? It have too much not-so-helpfull data for us, so it would be handy to enable it only for debugging purposes.

And thank you for great project!

**Comment by phillebaba** [comment]
I would suggest filtering metrics after scraping rather than implementing this in Spegel.

https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus/

Let me know if you have any other questions about this.
