### ISSUE TITLE
Memory leaking leads to OOMs

### ISSUE THREAD

**Issue by evgkrsk** [XenitAB/spegel#259]
Somehow all spegel's pods in my test cluster have linearly increasing memory usage that already killed one of pods twice in 1 day due to OOM (limit is 320Mi).

How can I help to debug such issue?

**Comment by evgkrsk** [comment]
Seems like disabling tags resolution helps to prevent OOMs: 
<img width="1596" alt="image" src="https://github.com/XenitAB/spegel/assets/79869/d2aa0fb5-bc58-4b93-b92c-b58688beb659">

**Comment by phillebaba** [comment]
That is an interesting finding. I can't really see how resolving tags would effect memory usage. Could I ask which version of Spegel you are using and what Kubernetes flavor you are deploying on.

**Comment by phillebaba** [comment]
@evgkrsk  I have not come up with a method of reproducing this. I just released v0.0.15 which contains the fix https://github.com/libp2p/go-libp2p-kad-dht/pull/960 which seems to have caused memory leaks during lookups. Could you try this new version and see if you experience the same issues?

**Comment by phillebaba** [comment]
@evgkrsk any updates?

**Comment by evgkrsk** [comment]
Issue resolved :-)
<img width="1571" alt="image" src="https://github.com/XenitAB/spegel/assets/79869/860ef88a-bad6-47e4-bc80-e702b2dd78c7">
