### ISSUE TITLE
Getting lots of 500s "mirror resolve retries exhausted for key"

### ISSUE THREAD

**Issue by kashak88** [XenitAB/spegel#265]
Hello, trying out spegel and facing these errors across the map:
```
{"level":"info","ts":1699886843.334517,"caller":"registry/registry.go:174","msg":"handling mirror request from external node","path":"/v2/p2m-qa/silo-p2m-qa-subtemplate-silo/manifests/sha256:2520965b7b02cd4c5090f635622c92c4dfd2446a2d9332106ae140a1e1eb7bc4","ip":"100.96.35.1"}
{"level":"error","ts":1699886843.3367004,"caller":"gin@v0.0.9/logger.go:62","msg":"","path":"/v2/p2m-qa/silo-p2m-qa-subtemplate-silo/manifests/sha256:2520965b7b02cd4c5090f635622c92c4dfd2446a2d9332106ae140a1e1eb7bc4","status":500,"method":"GET","latency":0.002227242,"ip":"100.96.35.1","handler":"mirror","error":"mirror resolve retries exhausted for key: sha256:2520965b7b02cd4c5090f635622c92c4dfd2446a2d9332106ae140a1e1eb7bc4","stacktrace":"github.com/xenitab/pkg/gin.NewEngine.Logger.func1\n\t/go/pkg/mod/github.com/xenitab/pkg/gin@v0.0.9/logger.go:62\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009"}
```
```
Containers:
  p2m-qa-subtemplate-silo:
    Container ID:  containerd://09110087199b09a31ce246c2be47d4046116f9bc64d927b4262036f56028e20b
    Image:         privateharborrepo.com/p2m-qa/silo-p2m-qa-subtemplate-silo:70
    Image ID:      privateharborrepo.com/p2m-qa/silo-p2m-qa-subtemplate-silo@sha256:2520965b7b02cd4c5090f635622c92c4dfd2446a2d9332106ae140a1e1eb7bc4
```
Containerd config.toml:
```
## template: jinja

# Use config version 2 to enable new configuration fields.
# Config file is parsed as version 1 by default.
version = 2

imports = ["/etc/containerd/conf.d/*.toml"]

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "projects.registry.vmware.com/tkg/pause:3.6"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
  [plugins."io.containerd.grpc.v1.cri".containerd]
    discard_unpacked_layers = false
```
spegel-values.yaml:
```
...
spegel:
  # -- Registries for which mirror configuration will be created.
  registries:
    - https://docker.io
    - https://ghcr.io
    - https://quay.io
    - https://mcr.microsoft.com
    - https://public.ecr.aws
    - https://gcr.io
    - https://registry.k8s.io
    - https://k8s.gcr.io
    - https://lscr.io
    - https://privateharborrepo.com
...
```

Is there something obvious that we're missing here? It seems to work just fine at other times, although I am still trying to figure out what defines "fine" :)
self hosted Harbor Version v2.7.1-6015b3ef - changed the url for obvious reasons
nodes: v1.23.10+vmware.1 Ubuntu 20.04.5 LTS   5.4.0-135-generic   containerd://1.6.6

**Comment by phillebaba** [comment]
@kashak88 what CNI are you running?

**Comment by kashak88** [comment]
```
[x@util-ansible ~]# kubectl -n kube-system get pod
NAME                                                      READY   STATUS    RESTARTS      AGE
antrea-agent-29xdt                                        2/2     Running   0             7d22h
antrea-agent-4tpsx                                        2/2     Running   0             12d
antrea-agent-6z8xp                                        2/2     Running   0             12d
antrea-agent-bb6ph                                        2/2     Running   0             24h
antrea-controller-56bdcc4f86-n9fdw                        1/1     Running   0             12d
coredns-7f4b78dcb5-8bm6t                                  1/1     Running   0             12d
```
Antrea by the looks of it

**Comment by phillebaba** [comment]
Never heard of that project before. I will need to have a look at how they implement host and node ports. I know that other people are having issues when using Cilium or running the CNI with IPVS. Adding a CNI section to the compatibility list might be a good idea, as I do not have time to test all possible CNIs all the time.

The main issue is that a built Spegel based on how Calico with Iptables works, which may not work with other configurations. I have been thinking about how to change this to increase the compatibility in the future, without negatively affecting existing deployments.

**Comment by kashak88** [comment]
The reason I said that it appears to work fine is because according to your docs, the success is measured by seeing these 2:
```
{"level":"info","ts":1692304805.9038486,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/library/nginx/blobs/sha256:1cb127bd932119089b5ffb612ffa84537ddd1318e6784f2fce80916bbb8bd166","status":200,"method":"GET","latency":0.005075836,"ip":"172.18.0.5","handler":"mirror"}

{"level":"info","ts":1692304805.9035861,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/library/nginx/blobs/sha256:1cb127bd932119089b5ffb612ffa84537ddd1318e6784f2fce80916bbb8bd166","status":200,"method":"GET","latency":0.003644997,"ip":"172.18.0.5","handler":"blob"}
```
I do see those with both our current antrea and calico (vmware tanzu officially supports it so I gave it a whirl in a test cluster). FWIW calico cluster also spits those 500s errors but as you said it's expected.
I guess the massive amount of these error logs making into datadog is what had us confused. Each missing image spits out a lot of logs and when you have lots pods it becomes hard to see if stuff is working with errors taking up 80% of all logs :)

If I may suggest, it would be nice to be able to supress some of this noise with LOG LEVEL control and maybe explicitly log simpler messages like "node X successfully mirrored a request by node Y to pull Z image" or something like that.

**Comment by phillebaba** [comment]
I agree with you that it gets confusing as we hard trained to link 500 errors with something bad. I also think that the error should cause a 404 instead as the image cannot be found. 

The issue of logging when an image is successfully pulled is that Spegel has no way of knowing when it occurs. An image pull consists of multiple HTTP requests done async, without any promise that all requests will be made at all. I will probably change the 500 to a 404 and add an option to control log level. Additionally the FAQ requires steps to verify that things are working properly, as there is too much confusion about it.

**Comment by phillebaba** [comment]
Closing as this is expected behavior, but we should instead look at better ways to indicate that things are working properly.
