### ISSUE TITLE
Running Out of Disk Space After Installation

### ISSUE THREAD

**Issue by rohitraut3366** [XenitAB/spegel#282]
-  As mentioned in the Compatibility document, we have disabled discard unpacked layers and this causing node to run of disk space.
```
[plugins."io.containerd.grpc.v1.cri".containerd]
   discard_unpacked_layers = false
```

Support to clean up images that are not used/pulled by other node in x-min

**Comment by rohitraut3366** [comment]
Hi, the issue has been resolved by adjusting the garbage collector configuration.

**Comment by phillebaba** [comment]
@rohitraut3366 could you share any configuration changes that you made so that we can document them?

**Comment by oscarsiles** [comment]
Not the OP, but I fixed this by changing these [kubelet settings](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) (defaults shown):

```
imageMaximumGCAge: 0s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
```
