### ISSUE TITLE
EKS kubelet fail to start with latest 1.29 AMI - `amazon-eks-node-1.29-v20240129`

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/spegel#350]
Update for the thread, I've had kubelet fail to start with the above patch on the latest 1.29 AMI - `amazon-eks-node-1.29-v20240129`.

Not sure why yet just thought I'd raise it as commenting out the userData patch got the nodes up and running.

_Originally posted by @danielloader in https://github.com/XenitAB/spegel/issues/217#issuecomment-1926762308_

**Comment by phillebaba** [comment]
@danielloader @tico24 I created a new issue to track the new Kubernetes version. Sadly I am not a heavy EKS user so it would take me a bit of time to get things running with a test environment. It would be great if we could work together to get the changes required documented for others.

**Comment by joryirving** [comment]
We had the same issue with 1.28. Had to comment out the userData

**Comment by tico24** [comment]
Raised an issue here: https://github.com/awslabs/amazon-eks-ami/issues/1628

**Comment by phillebaba** [comment]
I think a good first step is to SSH on to the VM and check the config file, containerd logs and kubelet logs to see if there is anything obvious going on.

I have observed that Containerd has been upgraded to 1.7 lately which could have an impact on the configuration changes.

**Comment by tico24** [comment]
I can't get to the VM to do that.

**Comment by tico24** [comment]
As you can see from my conversation in the aws issue, the problem is that they don't preload the containerd config any more. So the workaround is to inject the entire config and then tell the bootstrap script to use it. 

In this example, I steal the config from the tag relating to the AMI I am using, and then the rest is essentially the same as before.

```bash
#!/bin/bash
set -ex

# We copy in the default containerd config from amazon-eks-ami and then overwrite the discard_unpacked_layers value
# https://github.com/awslabs/amazon-eks-ami/blob/master/files/containerd-config.toml
# `discard_unpacked_layers = false` is overwritten to `false` for Spegel.
curl -s https://raw.githubusercontent.com/awslabs/amazon-eks-ami/v20240202/files/containerd-config.toml -o /etc/containerd/config-pipekit.toml
cat /etc/containerd/config-pipekit.toml | sed -E 's/discard_unpacked_layers = true/discard_unpacked_layers = false/g' > /etc/containerd/config-pipekit.toml

cat <<-EOF > /etc/profile.d/bootstrap.sh
export CONTAINERD_CONFIG_FILE=/etc/containerd/config-pipekit.toml
EOF
sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
```

**Comment by phillebaba** [comment]
Thanks for moving the issue forward and getting an explanation for what the issue is. Long term I think that enabling imports would be a good idea. Hopefully we can get this resolved quickly with a long term solution.

**Comment by phillebaba** [comment]
@tico24  @danielloader https://github.com/awslabs/amazon-eks-ami/pull/1630 has been merged but we are still waiting for a release of the AMI. When this happens could one of you help documenting the new method to configured Containerd?

**Comment by tico24** [comment]
Yes, possibly.

It's Kubecon season so my free time is sparse this month. But I'll get to it eventually.

**Comment by phillebaba** [comment]
There is now a release containing the new option to override Containerd config. If someone has time to test and verify the new userdata script that would be great! I had a look at the old examples for user data and had a try to create something that I think would work.

```shell
#!/bin/bash
set -ex

cat > /etc/containerd/config.d/spegel.toml <<EOL
[plugins."io.containerd.grpc.v1.cri".registry]
   config_path = "/etc/containerd/certs.d"
[plugins."io.containerd.grpc.v1.cri".containerd]
   discard_unpacked_layers = false
EOL 

/etc/eks/bootstrap.sh
```

We can close this issue when the compatibility guide has been updated.
https://github.com/XenitAB/spegel/blob/main/docs/COMPATIBILITY.md

**Comment by danielloader** [comment]
I gave that a try and the nodes wouldn't come up and register on the EKS control plane, didn't have time to debug it - but as a loose warning to anyone trying this to do it on a new node group or karpenter node pool.

**Comment by nickpetrovic** [comment]
@phillebaba FWIW your solution works for me. I'm using EKS 1.29 with the amazon-eks-node-1.29-v20240307 AMI.

**Comment by phillebaba** [comment]
@nickpetrovic I appreciate the info, I will add this to the documentation so we can close the issue.
