### ISSUE TITLE
Images are always pulled from upstream

### ISSUE THREAD

**Issue by joejulian** [XenitAB/spegel#377]
### Spegel version

v0.0.18

### Kubernetes distribution

vanilla

### Kubernetes version

v1.26.7

### CNI

calico

### Describe the bug

Image requests are always being pulled from upstream, even if another node has downloaded the image. This is a regression from v0.0.17 that's working fine.

**Comment by phillebaba** [comment]
This sounds like something has gone wrong with your Containerd config? Are you seeing requests coming into to Spegel that are returning 404 or 500 status codes or are you seeing no logs at all?

Could you share logs from Spegel to give me some more insight?

**Comment by joejulian** [comment]
Getting 200s. I'll try to find some time to get logs today. Replacing v0.0.18 with v0.0.17 fixes the problem so unless a config requirement changed in containerd, it shouldn't be that.

**Comment by sonyafenge** [comment]
> Getting 200s. I'll try to find some time to get logs today. Replacing v0.0.18 with v0.0.17 fixes the problem so unless a config requirement changed in containerd, it shouldn't be that.

retested on v0.0.18, cannot repro the issue.

**Comment by phillebaba** [comment]
@joejulian still seeing this issue? The main issue that causes this is when something happens to the Containerd configuration which results in image pulls not being mirrored. This was the case in #350.

I have a hard time understanding how there would be differences between these two versions as the end to end tests will air gap the nodes allowing images to only be pulled through Spegel.

**Comment by joejulian** [comment]
After downgrading and upgrading again, the problem went away. :shrug:.

Closing
